"""The golden-vector corpus against a real PostGIS — pins the DEPLOYED v2 identity
recipe byte-identical to the pure-Python reference.

Recipe v2 (migration 0008, ADR-007) is engine-independent: the corpus
(scripts/data/dedup_golden_vectors_v2.json) is generated by
``domain/geometry_identity`` with no database, and EVERY vector is strict on
every engine — the v1 strict/advisory split (GEOS-build-sensitive vectors) is
gone. CI's container and Cloud SQL must produce identical digests; the deploy
canary (``scripts/dedup_vectors.py --check``) re-validates this same corpus
against the live Cloud SQL engine after each migrate. Parity is pinned at two
levels: the sha256 digests AND the raw ``canonical_bytes`` serialization, so an
assembly/sort/endianness divergence cannot hide behind a digest coincidence.
"""

from __future__ import annotations

import importlib.util
import json
import sys
from pathlib import Path

import pytest
from sqlalchemy import text
from sqlalchemy.exc import DBAPIError

from geoid.domain import geometry_identity
from geoid.domain.geometry_format import decode_geometry
from geoid.repositories._pg_errors import SQLSTATE_DEGENERATE_GEOMETRY, sqlstate_of

pytestmark = pytest.mark.integration

ROOT = Path(__file__).resolve().parents[2]
FIXTURE_PATH = ROOT / "scripts" / "data" / "dedup_golden_vectors_v2.json"

_FIXTURE = json.loads(FIXTURE_PATH.read_text())
_VECTORS = _FIXTURE["vectors"]
_HASH_VECTORS = [vector for vector in _VECTORS if vector["expect"] == "hash"]
_ERROR_VECTORS = [vector for vector in _VECTORS if vector["expect"] == "error"]
_WKT_VECTORS = [vector for vector in _VECTORS if vector.get("wkt")]


def _load_dedup_vectors():
    spec = importlib.util.spec_from_file_location(
        "dedup_vectors", ROOT / "scripts" / "dedup_vectors.py"
    )
    module = importlib.util.module_from_spec(spec)
    sys.modules["dedup_vectors"] = module
    spec.loader.exec_module(module)
    return module


dedup_vectors = _load_dedup_vectors()

_GEOM = "ST_SetSRID(ST_GeomFromGeoJSON(:geojson), 4326)"  # the production parse path
_V2_SQL = text(f"SELECT encode(geoid_geom_hash_v2({_GEOM}), 'hex')")
_WRAPPER_SQL = text(f"SELECT encode(geoid_geom_hash_default({_GEOM}), 'hex')")
_BYTES_SQL = text(f"SELECT geoid_canonical_bytes_v2({_GEOM})")
_WKT_SQL = text("SELECT encode(geoid_geom_hash_v2(ST_GeomFromText(:wkt, 4326)), 'hex')")


async def _digest(session, stmt, vector) -> str:
    params = {"geojson": json.dumps(vector["geojson"])}
    return (await session.execute(stmt, params)).scalar_one()


@pytest.fixture
def sync_conn(_migrated):
    import psycopg

    dsn = _migrated.replace("postgresql+asyncpg://", "postgresql://")
    with psycopg.connect(dsn, autocommit=True) as conn:
        yield conn


@pytest.mark.parametrize("vector", _HASH_VECTORS, ids=lambda vector: vector["name"])
async def test_deployed_digest_matches_fixture_and_reference(session, vector):
    deployed = await _digest(session, _V2_SQL, vector)
    assert deployed == vector["sha256"], (
        f"deployed geoid_geom_hash_v2 drifted from the pinned corpus on "
        f"{vector['name']!r} — the SQL recipe no longer matches the frozen spec"
    )
    assert geometry_identity.geom_hash_v2(vector["geojson"]).hex() == vector["sha256"], (
        f"the Python reference drifted from the pinned corpus on {vector['name']!r}"
    )


@pytest.mark.parametrize("vector", _HASH_VECTORS, ids=lambda vector: vector["name"])
async def test_canonical_bytes_parity_sql_vs_reference(session, vector):
    # Byte-level, not just digest-level: an assembly/sort/endianness divergence
    # must surface as the exact differing bytes.
    sql_bytes = (
        await session.execute(_BYTES_SQL, {"geojson": json.dumps(vector["geojson"])})
    ).scalar_one()
    assert bytes(sql_bytes) == geometry_identity.canonical_bytes(vector["geojson"])


async def test_wrapper_is_flipped_to_v2_for_every_vector(session):
    # Migration 0008 re-points geoid_geom_hash_default (the arbiter's one entry
    # point) at the v2 recipe — dedup and identity flip together.
    for vector in _HASH_VECTORS:
        wrapper = await _digest(session, _WRAPPER_SQL, vector)
        assert wrapper == vector["sha256"], vector["name"]


@pytest.mark.parametrize("vector", _ERROR_VECTORS, ids=lambda vector: vector["name"])
async def test_degenerate_vector_raises_gd001_in_sql_and_the_reference(session, vector):
    with pytest.raises(DBAPIError) as exc_info:
        await _digest(session, _V2_SQL, vector)
    assert sqlstate_of(exc_info.value) == SQLSTATE_DEGENERATE_GEOMETRY
    await session.rollback()
    with pytest.raises(geometry_identity.DegenerateGeometryError):
        geometry_identity.geom_hash_v2(vector["geojson"])


@pytest.mark.parametrize("vector", _WKT_VECTORS, ids=lambda vector: vector["name"])
async def test_wkt_form_converges_on_the_geojson_digest(session, vector):
    # Production converts WKT via the app codec (shapely) before the DB ever sees
    # it; pin BOTH that path and the DB's own WKT parser onto the same digest.
    assert geometry_identity.geom_hash_v2(decode_geometry(vector["wkt"])).hex() == vector["sha256"]
    db_wkt = (await session.execute(_WKT_SQL, {"wkt": vector["wkt"]})).scalar_one()
    assert db_wkt == vector["sha256"]


async def test_v1_recipe_function_is_gone(session):
    # 0008 drops the GEOS-bound geoid_geom_hash(geometry, float8): no live
    # engine-dependent hash may stay callable on an identity database.
    count = (
        await session.execute(
            text("SELECT count(*) FROM pg_proc WHERE proname = 'geoid_geom_hash'")
        )
    ).scalar_one()
    assert count == 0


def test_check_vectors_passes_in_full_on_any_engine(sync_conn):
    # The script the deploy canary and bootstrap run: under v2 there is no
    # advisory drift allowance — every vector must match on this container
    # exactly as on Cloud SQL.
    run_sql = dedup_vectors._psycopg_run_sql(sync_conn)
    dedup_vectors.ensure_v2_deployed(run_sql)
    report = dedup_vectors.check_vectors(run_sql, dedup_vectors.load_fixture())
    assert report.failures == ()
    assert report.passed == len(_VECTORS)
