#!/usr/bin/env python3
"""Golden vectors for the identity recipe (``geoid_geom_hash_v2``, recipe v2).

Recipe v2 (ADR-007, migration 0008) is engine-independent: an integer-lattice
canonicalization owned entirely by this repo, with a pure-Python reference
implementation (``geoid.domain.geometry_identity``) byte-identical to the SQL.
The corpus is therefore **generated by the Python reference, no database
involved** — and ``--check`` verifies that the *deployed* SQL function computes
the same digests, so its meaning is "deployed function ≡ Python reference":

    uv run python scripts/dedup_vectors.py --generate
    uv run python scripts/dedup_vectors.py --check [--dsn postgresql://...]

Vectors are **GeoJSON-keyed** (production's only geometry parse path is
``ST_GeomFromGeoJSON``, place_repo.py); a couple carry a paired ``wkt`` form to
pin WKT→GeoJSON convergence through the app codec. ``expect`` is ``"hash"`` (a
pinned sha256) or ``"error"`` (a lattice-degenerate geometry the recipe must
REJECT: SQLSTATE GD001 in SQL, ``DegenerateGeometryError`` in Python).

``--check`` needs a migrated database (it probes for ``geoid_geom_hash_v2`` and
tells you to run ``geoid migrate`` if absent) and also asserts the deployed
``geoid_geom_hash_default`` wrapper — the arbiter's actual entry point — matches
every digest. It is the post-deploy Cloud Run canary job and a bootstrap step.

``--generate`` recomputes the corpus from the reference and REFUSES to overwrite
a committed fixture whose digests differ, unless ``--force``: under v2, digest
drift can only mean the recipe *code* changed — a recipe-version event, never a
casual fix. The fixture is deterministic (no timestamps): regenerating on an
unchanged recipe is byte-identical.

Exit codes (CLI):
    0 ok · 1 step failed · 2 config/usage error · 3 identity digest drift
"""

from __future__ import annotations

import argparse
import json
import os
import re
from collections.abc import Callable
from dataclasses import dataclass
from pathlib import Path
from typing import Literal

from geoid.domain.geometry_format import decode_geometry
from geoid.domain.geometry_identity import DegenerateGeometryError, geom_hash_v2

REPO_ROOT = Path(__file__).resolve().parents[1]
FIXTURE_PATH = REPO_ROOT / "scripts" / "data" / "dedup_golden_vectors_v2.json"

RECIPE_VERSION = "v2"
SQLSTATE_DEGENERATE = "GD001"

# The deployed v2 function and the wrapper the arbiter CTE actually calls, fed
# through the SAME parse path production uses (ST_GeomFromGeoJSON).
CHECK_SQL_V2 = (
    "SELECT encode(geoid_geom_hash_v2(ST_SetSRID(ST_GeomFromGeoJSON(%(geojson)s), 4326)), 'hex')"
)
CHECK_SQL_WRAPPER = (
    "SELECT encode(geoid_geom_hash_default("
    "ST_SetSRID(ST_GeomFromGeoJSON(%(geojson)s), 4326)), 'hex')"
)
PROBE_SQL = "SELECT count(*) FROM pg_proc WHERE proname = 'geoid_geom_hash_v2'"

# run_sql(query, params) -> first column of the first row. Injected so the same
# logic runs over psycopg (bootstrap/CLI) or any other scalar-returning executor.
RunSQL = Callable[..., str]


class ConfigError(Exception):
    """Bad or missing configuration — exit 2, nothing was touched."""


class StepError(Exception):
    """A check/generate step failed — exit 1; the message carries remediation hints."""


@dataclass(frozen=True)
class VectorCase:
    name: str
    geojson: dict
    expect: Literal["hash", "error"] = "hash"
    wkt: str | None = None  # paired WKT form: pins WKT->GeoJSON codec convergence
    same_as: str | None = None
    note: str | None = None


def _polygon(*rings) -> dict:
    return {"type": "Polygon", "coordinates": [list(ring) for ring in rings]}


_SQUARE = _polygon([[0, 0], [1, 0], [1, 1], [0, 1], [0, 0]])

VECTOR_CASES: tuple[VectorCase, ...] = (
    VectorCase(
        name="baseline_unit_square",
        geojson=_SQUARE,
        wkt="POLYGON((0 0,1 0,1 1,0 1,0 0))",
        note="canonical CCW unit square on the 1e-7 lattice (~1cm/vertex); the paired "
        "wkt pins WKT->GeoJSON codec convergence onto the same digest",
    ),
    VectorCase(
        name="ring_start_rotation",
        geojson=_polygon([[1, 1], [0, 1], [0, 0], [1, 0], [1, 1]]),
        same_as="baseline_unit_square",
        note="same ring, different start vertex — min-vertex rotation collapses it",
    ),
    VectorCase(
        name="cw_winding",
        geojson=_polygon([[0, 0], [0, 1], [1, 1], [1, 0], [0, 0]]),
        same_as="baseline_unit_square",
        note="same ring, clockwise winding — CCW orientation collapses it",
    ),
    VectorCase(
        name="hole_order_canonical",
        geojson=_polygon(
            [[0, 0], [10, 0], [10, 10], [0, 10], [0, 0]],
            [[2, 2], [3, 2], [3, 3], [2, 3], [2, 2]],
            [[6, 6], [7, 6], [7, 7], [6, 7], [6, 6]],
        ),
        note="two-hole polygon",
    ),
    VectorCase(
        name="hole_order_swapped",
        geojson=_polygon(
            [[0, 0], [10, 0], [10, 10], [0, 10], [0, 0]],
            [[6, 6], [7, 6], [7, 7], [6, 7], [6, 6]],
            [[2, 2], [3, 2], [3, 3], [2, 3], [2, 2]],
        ),
        same_as="hole_order_canonical",
        note="holes listed in the other order — canonical-bytes hole sort collapses it",
    ),
    VectorCase(
        name="multipart_order_canonical",
        geojson={
            "type": "MultiPolygon",
            "coordinates": [
                [[[0, 0], [1, 0], [1, 1], [0, 1], [0, 0]]],
                [[[5, 5], [6, 5], [6, 6], [5, 6], [5, 5]]],
            ],
        },
        note="two-part multipolygon",
    ),
    VectorCase(
        name="multipart_order_swapped",
        geojson={
            "type": "MultiPolygon",
            "coordinates": [
                [[[5, 5], [6, 5], [6, 6], [5, 6], [5, 5]]],
                [[[0, 0], [1, 0], [1, 1], [0, 1], [0, 0]]],
            ],
        },
        same_as="multipart_order_canonical",
        note="parts listed in the other order — canonical-bytes part sort collapses it",
    ),
    VectorCase(
        name="subgrid_jitter",
        geojson=_polygon([[1e-8, 0], [1, 0], [1, 1], [0, 1], [1e-8, 0]]),
        same_as="baseline_unit_square",
        note="1e-8 jitter, below the 1e-7 lattice — quantization absorbs it",
    ),
    VectorCase(
        name="consecutive_duplicate_vertex",
        geojson=_polygon([[0, 0], [1, 0], [1, 0], [1, 1], [0, 1], [0, 0]]),
        same_as="baseline_unit_square",
        note="doubled vertex — coincident lattice runs collapse (a repeated vertex "
        "carries zero shape information at the identity precision)",
    ),
    VectorCase(
        name="wraparound_duplicate",
        geojson=_polygon([[0, 0], [1, 0], [1, 1], [0, 1], [0, 0], [0, 0]]),
        same_as="baseline_unit_square",
        note="duplicate run straddling the ring closure — the cyclic wrap-around trim "
        "catches what a forward-only pass would miss",
    ),
    VectorCase(
        name="collinear_extra_vertex",
        geojson=_polygon([[0, 0], [0.5, 0], [1, 0], [1, 1], [0, 1], [0, 0]]),
        note="baseline square plus a collinear midpoint vertex — deliberately its OWN "
        "digest: the recipe never simplifies, so an inserted vertex is detectable",
    ),
    VectorCase(
        name="supragrid_shift",
        geojson=_polygon([[0.001, 0], [1, 0], [1, 1], [0, 1], [0.001, 0]]),
        note="0.001-degree shift, far above the lattice — a different place, own digest",
    ),
    VectorCase(
        name="cell_straddle_low",
        geojson=_polygon([[20.00000004, 20], [21, 20], [21, 21], [20, 21], [20.00000004, 20]]),
        note="x = 20 + 0.4 cells, quantizes DOWN — with cell_straddle_high this pins "
        "the known cell-boundary caveat (the lattice is absolute, not a radius). "
        "Strict under v2: the rounding is ours, no GEOS build involved.",
    ),
    VectorCase(
        name="cell_straddle_high",
        geojson=_polygon([[20.00000006, 20], [21, 20], [21, 21], [20, 21], [20.00000006, 20]]),
        note="x = 20 + 0.6 cells, quantizes UP — differs from cell_straddle_low though "
        "the inputs are 2e-8 apart. Was GEOS-build-sensitive (advisory) under v1; "
        "strict and engine-independent under v2.",
    ),
    VectorCase(
        name="negative_coords",
        geojson=_polygon([[-10, -10], [-9, -10], [-9, -9], [-10, -9], [-10, -10]]),
        note="negative coordinates (western/southern hemispheres) — pins the signed "
        "big-endian int8 serialization",
    ),
    VectorCase(
        name="negative_zero",
        geojson={"type": "Point", "coordinates": [-0.0, 0.0]},
        same_as="point_origin",
        note="IEEE -0.0 input — the integer lattice has no -0 by construction",
    ),
    VectorCase(
        name="high_precision_floats",
        geojson=_polygon(
            [
                [12.3456789012345, -45.6789012345678],
                [13.3456789012345, -45.6789012345678],
                [13.3456789012345, -44.6789012345678],
                [12.3456789012345, -44.6789012345678],
                [12.3456789012345, -45.6789012345678],
            ]
        ),
        note="15-significant-figure coordinates — exercises correctly-rounded number "
        "parsing (json-c strtod vs Python json) landing on the same doubles",
    ),
    VectorCase(
        name="world_extent",
        geojson=_polygon([[-180, -90], [180, -90], [180, 90], [-180, 90], [-180, -90]]),
        note="whole-world polygon: 2x its lattice area exceeds int64 max — pins the "
        "exact (numeric / Python int) shoelace accumulation",
    ),
    # --- Point / MultiPoint (ADR-005 types under the v2 recipe) -----------------
    VectorCase(
        name="point_origin",
        geojson={"type": "Point", "coordinates": [0, 0]},
        wkt="POINT(0 0)",
        note="canonical point at the origin — the Point analogue of baseline_unit_square",
    ),
    VectorCase(
        name="point_subgrid_jitter",
        geojson={"type": "Point", "coordinates": [1e-8, 0]},
        same_as="point_origin",
        note="1e-8 jitter, below the lattice — absorbed exactly as for a polygon vertex",
    ),
    VectorCase(
        name="tie_half_cell_x",
        geojson={"type": "Point", "coordinates": [5e-8, 0]},
        same_as="point_origin",
        note="x*1e7 is EXACTLY 0.5 after the one IEEE multiply — half-even rounds to 0 "
        "(not up to 1): the frozen tie rule",
    ),
    VectorCase(
        name="tie_half_cell_negative_y",
        geojson={"type": "Point", "coordinates": [0, -5e-8]},
        same_as="point_origin",
        note="y*1e7 is EXACTLY -0.5 — half-even rounds to 0 (not away to -1)",
    ),
    VectorCase(
        name="point_two_cells",
        geojson={"type": "Point", "coordinates": [2e-7, 0]},
        note="x on lattice index 2 — the collapse target for tie_even_up",
    ),
    VectorCase(
        name="tie_even_up",
        geojson={"type": "Point", "coordinates": [1.5e-7, 0]},
        same_as="point_two_cells",
        note="x*1e7 is EXACTLY 1.5 — half-even rounds UP to 2 (the even neighbour)",
    ),
    VectorCase(
        name="multipoint_canonical",
        geojson={"type": "MultiPoint", "coordinates": [[0, 0], [5, 5]]},
        note="two-point multipoint",
    ),
    VectorCase(
        name="multipoint_order_swapped",
        geojson={"type": "MultiPoint", "coordinates": [[5, 5], [0, 0]]},
        same_as="multipoint_canonical",
        note="members in the other order — the (x, y) member sort collapses it",
    ),
    VectorCase(
        name="multipoint_single",
        geojson={"type": "MultiPoint", "coordinates": [[0, 0]]},
        note="one-member multipoint — distinct from multipoint_duplicate_members "
        "(duplicates are KEPT) and from point_origin (type tag differs)",
    ),
    VectorCase(
        name="multipoint_duplicate_members",
        geojson={"type": "MultiPoint", "coordinates": [[0, 0], [1e-8, 0]]},
        note="two members on the SAME lattice point — kept as two (no silent merge), "
        "so this digest differs from multipoint_single",
    ),
    # --- Lattice degeneracy: the recipe must REJECT, never merge or vanish ------
    VectorCase(
        name="degenerate_sliver",
        geojson=_polygon([[0, 0], [1, 0], [1, 1e-8], [0, 1e-8], [0, 0]]),
        expect="error",
        note="sub-cell sliver: collapses to 2 lattice vertices. v1 MakeValid/"
        "ReducePrecision silently emptied such slivers (a silent identity merge); "
        "v2 rejects (SQL: GD001, Python: DegenerateGeometryError, API: 422)",
    ),
    VectorCase(
        name="degenerate_collinear",
        geojson=_polygon([[0, 0], [1, 0], [2, 1e-8], [0, 0]]),
        expect="error",
        note="collapses to three collinear lattice vertices — exact-zero shoelace",
    ),
    VectorCase(
        name="degenerate_bowtie",
        geojson=_polygon([[0, 0], [1, 1], [1, 0], [0, 1], [0, 0]]),
        expect="error",
        note="self-intersecting bowtie (v1's bowtie_makevalid reborn): its exact "
        "integer shoelace is zero — v2 refuses what v1 silently repaired/vanished",
    ),
)


@dataclass(frozen=True)
class VectorFailure:
    name: str
    expected: str
    actual: str


@dataclass(frozen=True)
class VectorReport:
    failures: tuple[VectorFailure, ...]
    passed: int


def reference_digest(geojson: dict) -> str:
    """The pure-Python reference digest (hex) for one geometry dict."""
    return geom_hash_v2(geojson).hex()


def load_fixture(path: Path = FIXTURE_PATH) -> dict:
    try:
        fixture = json.loads(path.read_text())
    except FileNotFoundError as exc:
        raise StepError(
            f"golden-vector fixture missing: {path}\n"
            "  Run from a synced checkout — scripts/data/ ships with the repo."
        ) from exc
    if fixture.get("recipe_version") != RECIPE_VERSION:
        raise StepError(
            f"fixture {path.name} carries recipe_version "
            f"{fixture.get('recipe_version')!r}, this script checks {RECIPE_VERSION!r}"
        )
    return fixture


def _sqlstate_of(exc: Exception) -> str | None:
    return getattr(exc, "sqlstate", None)


def check_vectors(run_sql: RunSQL, fixture: dict) -> VectorReport:
    """Recompute every pinned vector against the deployed SQL recipe.

    ``expect: hash`` vectors must match on BOTH ``geoid_geom_hash_v2`` and the
    ``geoid_geom_hash_default`` wrapper (proving the migration-0008 flip);
    ``expect: error`` vectors must raise SQLSTATE GD001.
    """
    failures: list[VectorFailure] = []
    passed = 0
    for vector in fixture["vectors"]:
        params = {"geojson": json.dumps(vector["geojson"])}
        if vector["expect"] == "error":
            try:
                actual = run_sql(CHECK_SQL_V2, params)
            except Exception as exc:  # noqa: BLE001 — classified by SQLSTATE below
                sqlstate = _sqlstate_of(exc)
                if sqlstate == SQLSTATE_DEGENERATE:
                    passed += 1
                else:
                    failures.append(
                        VectorFailure(
                            vector["name"],
                            f"SQLSTATE {SQLSTATE_DEGENERATE}",
                            f"SQLSTATE {sqlstate!r} ({exc})",
                        )
                    )
                continue
            failures.append(
                VectorFailure(vector["name"], f"SQLSTATE {SQLSTATE_DEGENERATE}", f"digest {actual}")
            )
            continue
        ok = True
        for label, query in (("geoid_geom_hash_v2", CHECK_SQL_V2), ("wrapper", CHECK_SQL_WRAPPER)):
            actual = run_sql(query, params)
            if actual != vector["sha256"]:
                failures.append(
                    VectorFailure(f"{vector['name']} [{label}]", vector["sha256"], actual)
                )
                ok = False
        if ok:
            passed += 1
    return VectorReport(tuple(failures), passed)


def ensure_v2_deployed(run_sql: RunSQL) -> None:
    """Fail with a clear hint when migration 0008 has not been applied yet."""
    if int(run_sql(PROBE_SQL)) < 1:
        raise StepError(
            "geoid_geom_hash_v2 is not deployed on this database — run `geoid migrate` "
            "(migration 0008) first; the v2 check validates the DEPLOYED function."
        )


def generate_fixture() -> dict:
    """Compute the corpus from the pure-Python reference (no database).

    Self-checks before returning: ``same_as`` pairs collapse, ``error`` cases
    raise ``DegenerateGeometryError``, and every paired ``wkt`` decodes (via the
    app's WKT codec) to a geometry with the identical digest.
    """
    digests: dict[str, str] = {}
    for case in VECTOR_CASES:
        if case.expect == "error":
            try:
                reference_digest(case.geojson)
            except DegenerateGeometryError:
                continue
            raise StepError(
                f"self-check failed: {case.name!r} should be rejected as lattice-"
                "degenerate but hashed — recipe or corpus bug; not writing the fixture"
            )
        digests[case.name] = reference_digest(case.geojson)
        if case.wkt is not None:
            converged = reference_digest(decode_geometry(case.wkt))
            if converged != digests[case.name]:
                raise StepError(
                    f"self-check failed: the WKT form of {case.name!r} does not "
                    "converge on the GeoJSON digest — codec or corpus bug"
                )
    for case in VECTOR_CASES:
        if case.same_as and digests[case.name] != digests[case.same_as]:
            raise StepError(
                f"self-check failed: {case.name!r} should canonicalize identically to "
                f"{case.same_as!r} but did not — recipe or corpus bug; not writing the fixture"
            )
    # Deterministic content (no timestamps): regenerating on an unchanged recipe
    # is byte-identical, which is itself a reproducibility check.
    return {
        "recipe_version": RECIPE_VERSION,
        "generated_by": (
            "scripts/dedup_vectors.py --generate — pure-Python reference "
            "(geoid.domain.geometry_identity), engine-independent (ADR-007)"
        ),
        "vectors": [
            {
                "name": case.name,
                "geojson": case.geojson,
                "wkt": case.wkt,
                "expect": case.expect,
                "sha256": digests.get(case.name),
                "same_as": case.same_as,
                "note": case.note,
            }
            for case in VECTOR_CASES
        ],
    }


def refuse_silent_regeneration(fixture: dict, out: Path, *, force: bool) -> None:
    """Refuse to overwrite a committed fixture whose digests differ (recipe-version
    event) unless ``--force``. A missing or same-digest fixture writes freely."""
    if force or not out.exists():
        return
    try:
        committed = json.loads(out.read_text())
    except (OSError, json.JSONDecodeError):
        return  # unreadable/corrupt committed file — overwriting it is the fix
    pinned = {v["name"]: v.get("sha256") for v in committed.get("vectors", [])}
    fresh = {v["name"]: v.get("sha256") for v in fixture["vectors"]}
    drifted = sorted(name for name in pinned.keys() & fresh.keys() if pinned[name] != fresh[name])
    if drifted:
        raise StepError(
            f"recomputed digests differ from the committed fixture for {drifted} — "
            "the recipe code changed. That is a RECIPE-VERSION EVENT (new migration, "
            "re-mint runbook), never a casual fix; pass --force only if that is intended."
        )


def _parse_args(argv: list[str] | None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Check the deployed identity recipe against the golden-vector "
        "corpus, or (re)generate the corpus from the pure-Python reference."
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="recompute the pinned vectors against the deployed geoid_geom_hash_v2",
    )
    parser.add_argument(
        "--generate",
        action="store_true",
        help="compute fresh digests from the Python reference and write the fixture "
        "(no database needed)",
    )
    parser.add_argument(
        "--dsn",
        default=None,
        help="libpq DSN/URL of the database for --check (default: GEOID_DATABASE_URL "
        "with any SQLAlchemy '+driver' suffix stripped — lets the Cloud Run canary "
        "job reuse the mounted asyncpg secret)",
    )
    parser.add_argument(
        "--fixture",
        type=Path,
        default=FIXTURE_PATH,
        help="fixture to check against (default: the committed corpus)",
    )
    parser.add_argument(
        "--out", type=Path, default=FIXTURE_PATH, help="where --generate writes the fixture"
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="allow --generate to overwrite a fixture whose digests differ "
        "(a recipe-version event)",
    )
    args = parser.parse_args(argv)
    if args.check == args.generate:
        raise ConfigError("pass exactly one of --check / --generate")
    if args.check and not args.dsn:
        args.dsn = _normalize_dsn(os.environ.get("GEOID_DATABASE_URL", ""))
        if not args.dsn:
            raise ConfigError("--check needs a database: pass --dsn or set GEOID_DATABASE_URL")
    return args


def _normalize_dsn(dsn: str) -> str:
    """Strip a SQLAlchemy driver suffix so psycopg/libpq accepts the URL.

    The deployed ``GEOID_DATABASE_URL`` is ``postgresql+asyncpg://…?host=/cloudsql/…``;
    psycopg wants plain ``postgresql://`` (the unix-socket ``?host=`` query form
    passes through to libpq untouched).
    """
    return re.sub(r"^postgresql\+\w+://", "postgresql://", dsn)


def _psycopg_run_sql(conn) -> RunSQL:
    def run_sql(query: str, params: dict | None = None) -> str:
        return conn.execute(query, params).fetchone()[0]

    return run_sql


def _run_check(args: argparse.Namespace) -> int:
    import psycopg

    try:
        with psycopg.connect(args.dsn, autocommit=True) as conn:
            run_sql = _psycopg_run_sql(conn)
            ensure_v2_deployed(run_sql)
            fixture = load_fixture(args.fixture)
            report = check_vectors(run_sql, fixture)
    except psycopg.Error as exc:
        print(f"✗ database error: {exc}")
        return 1
    for failure in report.failures:
        print(
            f"✗ vector {failure.name!r} drifted (expected {failure.expected}, got {failure.actual})"
        )
    print(f"{report.passed}/{len(fixture['vectors'])} vectors match")
    return 3 if report.failures else 0


def main(argv: list[str] | None = None) -> int:
    try:
        args = _parse_args(argv)
    except ConfigError as exc:
        print(f"✗ {exc}")
        return 2

    try:
        if args.generate:
            fixture = generate_fixture()
            refuse_silent_regeneration(fixture, args.out, force=args.force)
            args.out.parent.mkdir(parents=True, exist_ok=True)
            args.out.write_text(json.dumps(fixture, indent=2) + "\n")
            print(f"✓ wrote {len(fixture['vectors'])} vectors to {args.out}")
            print("  generated from the pure-Python reference (no engine dependence)")
            return 0
        return _run_check(args)
    except StepError as exc:
        print(f"✗ {exc}")
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
